version: '3.5'

# 自定义数据卷:
volumes:
  postgres_data:


######################################################


services:
  redis:
    image: redis:alpine
    container_name: redis2
    ports:
      - "6379:6379"

  db:
    image: postgres:10-alpine
    container_name: db
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data

