version: '2.2' # extends only support in 2.x


# 自定义数据卷:
volumes:
  nginx-shared:

services:
  #################### api service: base ##############################

  web: &web
    container_name: web
    build:
      context: .
      dockerfile: docker/web/Dockerfile
    env_file:
      - .env
#    depends_on:
#      - db
#      - redis
    working_dir: /app
    ports:
      - "8888:8888"
    volumes:
      - nginx-shared:/nginx
    command: docker/web/run_web.sh

